apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: k4e-examples-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/jakub-dzon/k4e-examples.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: random-server-image
spec:
  type: image
  params:
    - name: url
      value: quay.io/jdzon/random-server
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: random-server-build-pipeline
spec:
  resources:
    - name: app-git
      type: git
    - name: app-image
      type: image
  params:
    - name: imageTag
      type: string
      default: latest
      description: Tag for the built image
  tasks:
    - name: build-and-push
      taskRef:
        name: build-from-dockerfile
      params:
        - name: DOCKERFILE_PATH
          value: "./poc-demo/edge/random-server/Dockerfile"
        - name: IMAGE_TAG
          value: "$(params.imageTag)"
      resources:
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: image
            resource: app-image
