apiVersion: management.k4e.io/v1alpha1
kind: EdgeDeployment
metadata:
  name: os-stats
spec:
  deviceSelector:
    matchExpressions:
      - key: arch
        operator: In
        values: [x86_64, aarch64]
  data:
    paths:
      - source: stats
        target: statistics
  type: pod
  pod:
    spec:
      containers:
        - name: stats-collector
          image: quay.io/jdzon/os-stats:v2

